version: '3'

services:
    mongo:
        image: mongo:latest
        container_name: mongo_tkObat
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: p455w0rd
        volumes:
            - ./mongo:/mongo/db
    transaksi_service:
        build: ./transaksi_service
        container_name: transaksi
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./transaksi_service:/app
        ports:
            - 8000:8000
    user_service:
        build: ./user_service
        container_name: user
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./user_service:/app
        ports:
            - 8001:8000
    obat_service:
        build: ./obat_service
        container_name: obat
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        volumes:
            - ./obat_service:/app
        ports:
            - 8002:8000
